// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbpeyfietrwlhwcwqhjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticGV5ZmlldHJ3bGh3Y3dxaGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NDA5NjEsImV4cCI6MjA1NDQxNjk2MX0.A-K4DO6D2qQZ66qIXY4BlmoHxc-W5B0itV-HAAM84YA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

supabase.auth.onAuthStateChange(async (event, session) => {
  console.log("Auth event:", event);

  // When the user signs in or the token is refreshed, save a backup.
  if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
    if (session) {
      localStorage.setItem('supabase-session-backup', JSON.stringify(session));
    }
  }

  // If a token refresh fails, try to restore the session from the backup.
  // This often happens due to a 429 "Too Many Requests" error.
  if (event === 'TOKEN_REFRESH_FAILED') {
    console.warn('Token refresh failed. Attempting to restore from backup.');
    const backup = localStorage.getItem('supabase-session-backup');
    if (backup) {
      console.log('Restoring session from backup.');
      const backupSession = JSON.parse(backup);
      await supabase.auth.setSession({
        access_token: backupSession.access_token,
        refresh_token: backupSession.refresh_token,
      });
    }
  }
});